export const POST_LOAD_RANGE_PENDING   = 'POST_LOAD_RANGE_PENDING';
export const POST_LOAD_RANGE_FULFILLED = 'POST_LOAD_RANGE_FULFILLED';
export const POST_LOAD_RANGE_REJECTED  = 'POST_LOAD_RANGE_REJECTED';
