export const POST_LOAD_PAGE_PENDING   = 'POST_LOAD_PAGE_PENDING';
export const POST_LOAD_PAGE_FULFILLED = 'POST_LOAD_PAGE_FULFILLED';
export const POST_LOAD_PAGE_REJECTED  = 'POST_LOAD_PAGE_REJECTED';
export const POST_LOAD_BYID_PENDING   = 'POST_LOAD_BYID_PENDING';
export const POST_LOAD_BYID_FULFILLED = 'POST_LOAD_BYID_FULFILLED';
export const POST_LOAD_BYID_REJECTED  = 'POST_LOAD_BYID_REJECTED';
