export const POST_LOAD_PAGE_PENDING   = 'POST_LOAD_PAGE_PENDING';
export const POST_LOAD_PAGE_FULFILLED = 'POST_LOAD_PAGE_FULFILLED';
export const POST_LOAD_PAGE_REJECTED  = 'POST_LOAD_PAGE_REJECTED';
export const POST_LOAD_BYID_PENDING   = 'POST_LOAD_BYID_PENDING';
export const POST_LOAD_BYID_FULFILLED = 'POST_LOAD_BYID_FULFILLED';
export const POST_LOAD_BYID_REJECTED  = 'POST_LOAD_BYID_REJECTED';

export const COM_SAVE_PENDING   = 'COM_SAVE_PENDING';
export const COM_SAVE_FULFILLED = 'COM_SAVE_FULFILLED';
export const COM_SAVE_REJECTED  = 'COM_SAVE_REJECTED';
